In [1]:
import torch

In [2]:
theta_numerator = torch.arange(0, 32, 2).float()

In [3]:
theta_numerator

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
        28., 30.])

In [4]:
theta_numerator.shape

torch.Size([16])

In [6]:
x = torch.arange(64).reshape(1, 2, 8, 4)
x.shape

torch.Size([1, 2, 8, 4])

In [7]:
x_complex = torch.view_as_complex(x.float().reshape(*x.shape[:-1], -1, 2))

In [8]:
x_complex.shape

torch.Size([1, 2, 8, 2])

In [9]:
x

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31]],

         [[32, 33, 34, 35],
          [36, 37, 38, 39],
          [40, 41, 42, 43],
          [44, 45, 46, 47],
          [48, 49, 50, 51],
          [52, 53, 54, 55],
          [56, 57, 58, 59],
          [60, 61, 62, 63]]]])

In [10]:
x_complex

tensor([[[[ 0.+1.j,  2.+3.j],
          [ 4.+5.j,  6.+7.j],
          [ 8.+9.j, 10.+11.j],
          [12.+13.j, 14.+15.j],
          [16.+17.j, 18.+19.j],
          [20.+21.j, 22.+23.j],
          [24.+25.j, 26.+27.j],
          [28.+29.j, 30.+31.j]],

         [[32.+33.j, 34.+35.j],
          [36.+37.j, 38.+39.j],
          [40.+41.j, 42.+43.j],
          [44.+45.j, 46.+47.j],
          [48.+49.j, 50.+51.j],
          [52.+53.j, 54.+55.j],
          [56.+57.j, 58.+59.j],
          [60.+61.j, 62.+63.j]]]])